export const APP_FEATURES=[
{
    id:"01",
    title:"Tailored Just for You",
    description:"Get interview questions and model answers based on your role,experience and specific focus areas."
},

{
    id:"02",
    title:"Learn at your Own Pace",
    description:"Expand answers only when you are ready.Dive deeper into concept instantly with AI-powered detailed explanations."
},

{
    id:"03",
    title:"Capture Your Insights",
    description:"Add personal notes to any question and pin important ones to the top-making your learning more organize and effective."
},

{
    id:"04",
    title:"Understand the 'Why' behind the Answer",
    description:"Beyond just answers- unlock detailed concept explanations generated by AI to help you understand the 'why' behind the answer."
},
{
    id:"05",
    title:"Save,Organize,and Revisit",
    description:"Easily save your interview sets,organize them neatly in your dashboard,and revisit them whenever you need."
},
];